logo: "/assets/images/logo.png"
description: >- # this means to ignore newlines until "baseurl:"
  Hubs is for anyone who wants to connect with others remotely!
  It's a great way to bring communities together in a shared virtual space.

  Host a conference, teach a class, showcase art, or just hang out with friends.
  Hubs makes it easy to connect and share images, videos, 3D models, and more.
  With Hubs' spatialized audio you can have conversations with everyone together or
  break out into smaller groups &mdash; just like you can in person.
baseurl: "/OnBoardXR_Landing_Page" # the subpath of your site, e.g. /blog
url: "https://futurestages.github.io" # the base hostname & protocol for your site, e.g. http://example.com
permalink: pretty
exclude: [ "node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",
           "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile", "docs/tests/" ]

search_enabled: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Build settings
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-feed
